feat: add validation for boolean
escaletech/go-escale pull request #6
Opened 2021-05-17 21:35 UTC by jessicasimplicio

2021-05-17 23:08 UTC, alinefr requested changes

2021-05-17 23:08 UTC, alinefr commented on envreader/bool.go
> +	ret, _ = strconv.ParseBool(val)
A validação do erro aqui é importante. ParseBool não deve aceitar qualquer string. Ele deve ser capaz de parsear "true" ou "false".
Por ex: e se eu usar
MYVAR=feijoada
r.BoolOrDefault("MYVAR", true)? 
```suggestion
        if ret, err := strconv.ParseBool(val); err == nil {
                return val
        }
```

2021-05-18 13:11 UTC, jessicasimplicio commented on envreader/bool.go
> +	fmt.Println(val)
não!! Eu estava testando e esqueci aí
valeu, Aline!

2021-05-18 13:14 UTC, jessicasimplicio commented on envreader/bool.go
> +	ret, _ = strconv.ParseBool(val)
faz total sentido!

2021-05-18 13:22 UTC, higfonseca commented on test/utils/envReaderUtils.go
> +			return "";
Não acredito que vá gerar erro, mas não precisa do `;` aqui. :)

2021-05-18 13:44 UTC, jessicasimplicio commented on test/utils/envReaderUtils.go
> +			return "";
boa!

2021-05-18 20:41 UTC, alinefr approved these changes

2021-05-19 14:51 UTC, higfonseca approved these changes

2021-05-19 14:54 UTC, merged